name: Test Hibernate ORM

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**/release_draft.yml'
      - '**/maven*.yml'
      - '**/*.md'
      - '**/docs/**'
      - '**/*.jpg'
      - '**/*.png'

jobs:
  test_hibernate:
    name: Hibernate ORM
    runs-on: ubuntu-20.04
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1
        name: Publish Snapshot
        with:
          job-id: jdk8
          arguments: publishToMavenLocal
      - name: clone hibernate_orm and run tests
        run: ./.github/scripts/check_commits.sh
        shell: bash
        env:
          HIBERNATE_COMMIT_ID: ${{ secrets.HIBERNATE_COMMIT_ID }}
