name: Test Debezium

# only on push or allow us to do this manually using workflow dispatch
on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  setup-postgresql-ubuntu:
    if: true # false to skip job during debug
    name: Setup PostgreSQL on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create hibernate_irm user
        run: |
          sudo -u postgres psql --command="CREATE USER hibernate_orm_test PASSWORD 'hibernate_orm_test'" --command="\du"
      - name: Create hibernate_orm_test database
        run: |
          sudo -u postgres createdb --owner=hibernate_orm_test hibernate_orm_test

  test_hibernate:
    name: Hibernate ORM
    runs-on: ubuntu-20.04
    #only for master
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1
        name: Publish Snapshot
        with:
          job-id: jdk8
          arguments: publishToMavenLocal
      - name: clone hibernate_orm and run tests
        run: |
          git clone --depth 1 https://github.com/hibernate/hibernate-orm.git
          cd hibernate-orm
          git apply ../test_data/0001-Changes-to-run-wrapper-driver.patch
          ./gradlew test -Pdb=amazon_ci -DdbHost=localhost -PexcludeTests=\*\*.XmlMappingTests\*\*
