name: 'Release to Maven'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - main-2.x
      - fix/env-var-signing-properties

permissions:
  contents: read

jobs:
  ubuntu-latest-jdbc-wrapper-release-to-maven:
    name: 'Build And Release to Maven'
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone Repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5
        with:
          distribution: 'corretto'
          java-version: 8
      - name: 'Build Driver'
        run: |
          ./gradlew --no-parallel --no-daemon -x test build
          ./gradlew --no-parallel --no-daemon -x test shadowJar
      - name: 'Strip GPG Passphrase'
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          printf '%s\n' "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --batch --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --export-secret-keys --armor "$GPG_KEY_ID" > /tmp/signing-key.asc
      - name: 'Publish to Maven'
        run: |
          ORG_GRADLE_PROJECT_signingKey=$(cat /tmp/signing-key.asc) ./gradlew --no-parallel --no-daemon publishToMavenLocal -Prelease=true -PjacocoEnabled=false
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ""
