name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
      - main-2.x
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions: read-all

jobs:
  scorecard:
    name: 'Run OpenSSF Scorecard'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read
    steps:
      - name: 'Clone Repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          persist-credentials: false
      - name: 'Run Scorecard'
        uses: ossf/scorecard-action@ff5dd8929f96a8a4dc67d13f32b8c75057829621  # v2.4.0
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: true
      - name: 'Upload Scorecard SARIF'
        uses: github/codeql-action/upload-sarif@f35333b910470a5408cb081b68f0701254a7d27b  # v3.28.18
        with:
          sarif_file: scorecard-results.sarif
      - name: 'Upload Scorecard results'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6
        with:
          name: scorecard-results
          path: scorecard-results.sarif
          retention-days: 5
